version: "3.8"

services:
  ${LAB_NAME}_wazuh_manager:
    image: wazuh/wazuh-manager:4.4.0
    container_name: ${LAB_NAME}_wazuh_manager
    hostname: ${LAB_NAME}_wazuh_manager
    environment:
      - WAZUH_CLUSTER_KEY=ClusterKey123
    ports:
      - "${WAZUH_PORT_1514}:1514/udp"
      - "${WAZUH_PORT_1515}:1515"
      - "${WAZUH_PORT_55000}:55000"
    volumes:
      - ./data/${LAB_NAME}/wazuh_manager:/var/ossec/data
    networks:
      - "${LAB_NAME}_net"

  ${LAB_NAME}_wazuh_indexer:
    image: wazuh/wazuh-indexer:4.4.0
    container_name: ${LAB_NAME}_wazuh_indexer
    hostname: ${LAB_NAME}_wazuh_indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.name=${LAB_NAME}-cluster
      - node.name=${LAB_NAME}_wazuh_indexer
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/${LAB_NAME}/wazuh_indexer:/var/lib/wazuh-indexer
    networks:
      - "${LAB_NAME}_net"

  ${LAB_NAME}_wazuh_dashboard:
    image: wazuh/wazuh-dashboard:4.4.0
    container_name: ${LAB_NAME}_wazuh_dashboard
    hostname: ${LAB_NAME}_wazuh_dashboard
    environment:
      - WAZUH_API_URL=https://${LAB_NAME}_wazuh_manager
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=SecretPass123
    ports:
      - "${WAZUH_PORT_5601}:5601"
    networks:
      - "${LAB_NAME}_net"
    depends_on:
      - ${LAB_NAME}_wazuh_manager
      - ${LAB_NAME}_wazuh_indexer

  ${LAB_NAME}_mariadb:
    image: mariadb:10.6
    container_name: ${LAB_NAME}_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: app
      MYSQL_PASSWORD: vulnerables
    networks:
      - "${LAB_NAME}_net"

  ${LAB_NAME}_dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: ${LAB_NAME}_dvwa
    depends_on:
      - ${LAB_NAME}_mariadb
    environment:
      - MYSQL_HOST=${LAB_NAME}_mariadb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=vulnerables
      - MYSQL_DATABASE=dvwa
      - PHP_DISPLAY_ERRORS=1
      - DVWA_SECURITY=low
    networks:
      - "${LAB_NAME}_net"

  ${LAB_NAME}_attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    image: lab_attacker:latest
    container_name: ${LAB_NAME}_attacker
    command: sleep infinity
    volumes:
      - ./attacker/attacks:/opt/attacks:ro
    networks:
      - "${LAB_NAME}_net"

networks:
  ${LAB_NAME}_net:
    driver: bridge
    ipam:
      config:
        - subnet: "${LAB_SUBNET}"
