services:
  ${LAB_NAME}_wazuh_manager:
    image: wazuh/wazuh-manager:4.13.0
    container_name: ${LAB_NAME}_wazuh_manager
    hostname: ${LAB_NAME}_wazuh_manager
    restart: always
    environment:
      - WAZUH_CLUSTER_KEY=ClusterKey123
      - INDEXER_URL=http://${LAB_NAME}_wazuh_indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - DISABLE_FILEBEAT_CUSTOMIZE=true
    ports:
      - "${WAZUH_PORT_1514}:1514/udp"
      - "${WAZUH_PORT_1515}:1515"
      - "${WAZUH_PORT_55000}:55000"
    volumes:
      - ./wazuh_manager/data:/var/ossec/data
      - ./wazuh_manager/config/ossec.conf:/var/ossec/etc/ossec.conf:ro
      # Neutraliser totalement Filebeat interne (service s6)
      - /dev/null:/etc/services.d/filebeat/run
      - /dev/null:/etc/services.d/filebeat/finish
      # Partager les logs avec Filebeat externe
      - wazuh-logs:/var/ossec/logs
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_wazuh_manager ]

  ${LAB_NAME}_wazuh_indexer:
    image: wazuh/wazuh-indexer:4.13.0
    container_name: ${LAB_NAME}_wazuh_indexer
    hostname: ${LAB_NAME}_wazuh_indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./wazuh_indexer/data:/var/lib/wazuh-indexer
      # Monte la conf qui désactive le plugin de sécurité
      - ./wazuh_indexer/config/opensearch.yml:/usr/share/wazuh-indexer/opensearch.yml:ro
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_wazuh_indexer ]
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 20s
      timeout: 5s
      retries: 15

  ${LAB_NAME}_wazuh_dashboard:
    image: wazuh/wazuh-dashboard:4.13.0
    container_name: ${LAB_NAME}_wazuh_dashboard
    hostname: ${LAB_NAME}_wazuh_dashboard
    restart: always
    environment:
      - WAZUH_API_URL=http://${LAB_NAME}_wazuh_manager:55000
      - WAZUH_API_USER=admin
      - WAZUH_API_PASSWORD=admin
      - OPENSEARCH_HOSTS=http://${LAB_NAME}_wazuh_indexer:9200
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "${WAZUH_PORT_5601}:5601"
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_wazuh_dashboard ]
    depends_on:
      ${LAB_NAME}_wazuh_indexer:
        condition: service_healthy

  ${LAB_NAME}_filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: ${LAB_NAME}_filebeat
    user: root
    volumes:
      - wazuh-logs:/var/ossec/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${LAB_NAME}_filebeat_data:/usr/share/filebeat/data
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_filebeat ]
    depends_on:
      ${LAB_NAME}_wazuh_indexer:
        condition: service_healthy

  ${LAB_NAME}_mariadb:
    image: mariadb:10.6
    container_name: ${LAB_NAME}_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: app
      MYSQL_PASSWORD: vulnerables
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_mariadb ]

  ${LAB_NAME}_dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: ${LAB_NAME}_dvwa
    restart: always
    depends_on:
      ${LAB_NAME}_mariadb:
        condition: service_started
    environment:
      - MYSQL_HOST=${LAB_NAME}_mariadb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=vulnerables
      - MYSQL_DATABASE=dvwa
    networks:
      ${LAB_NAME}_net:
        aliases: [ ${LAB_NAME}_dvwa ]

volumes:
  wazuh-logs:
  ${LAB_NAME}_filebeat_data:

networks:
  ${LAB_NAME}_net:
    name: ${COMPOSE_PROJECT_NAME}_${LAB_NAME}_net
    driver: bridge
