services:
  nginx_reverse_proxy:
    image: nginx:stable
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      # Dossier où create_lab.sh dépose les confs générées
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Log nginx pour debug
      - ./nginx/logs:/var/log/nginx
    networks:
      - labnet_global
      - infrastructure_lab1_net   # <--- connexion directe au réseau du lab1

networks:
  labnet_global:
    driver: bridge
  infrastructure_lab1_net:
    external: true   # <--- très important pour rejoindre un réseau déjà créé
