services:
  nginx_reverse_proxy:
    image: nginx:stable
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - labnet_global

networks:
  labnet_global:
    driver: bridge
